spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb
    username: myuser
    password: mypassword

  mail:
    host: smtp.gmail.com
    port: 587
    username: gksxorb147@gmail.com # downpass
    password:
    properties:
      mail:
        smtp:
          timeout: 5000
          starttls:
            enable: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  redis:
    host:
      chat: localhost
      email: localhost
    port:
      chat: 6379
      email: 6380
    password:
      chat: redis-chat-pw
      email: redis-email-pw
    email:
      expire-time: 3 # 분

  security:
    oauth2:
      client:
        password-key: oauth2
        registration:
          google:
            client-id: 670687707962-k9gdlufh1kggejkvt8jvqnlmqs6sh9s7.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - profile
              - email

          kakao:
            client-id: 047d464876c4aa352beed70ab28fbd1d
            client-secret: zMNssX9yyvDCv6bZlRD8HIYLslg3znT9
            scope:
              - account_email
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post

          naver:
            client-id: U2Htq3Wug7aV_Tc8IFB0
            client-secret: Ee6YX0MVQx
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

jwt:
  secret: 18748a26-b13e-430f-a103-30b3684927db
  access-token-period: 3600000
  refresh-token-period: 86400000
  token-provider: down-server-jwt

logging:
  level:
    root: info
   # root: debug

api:
  version-path: /api/v1

file:
  upload:
    path: /static